version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - run: yarn install

  uat_deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - $UAT_VM_SSH_FINGERPRINT
      - run:
          name: Deploy to GCP Compute Engine
          command: |
            ssh -o StrictHostKeyChecking=no $VM_USER@$UAT_VM_IP "cd /home/dino_wu/musense-trend-next/ && sudo git pull && sudo yarn install && sudo rm -r .next/ && sudo yarn build:uat:local && sudo pm2 restart musense-homepage"

  production_deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - $PROD_VM_SSH_FINGERPRINT
      - run:
          name: Deploy to GCP Compute Engine
          command: |
            ssh -o StrictHostKeyChecking=no $VM_USER@$PROD_VM_IP "cd /home/dino_wu/musense-trend-next/ && sudo git pull && sudo yarn install && sudo rm -r .next/ && sudo yarn build && sudo pm2 restart musense-homepage"

workflows:
  build-and-deploy:
    jobs:
      - build
      - uat_deploy:
          requires:
            - build
          filters:
            branches:
              only: uat
      - production_deploy:
          requires:
            - build
          filters:
            branches:
              only: main
